### ISSUE TITLE
Get rid of rndaddentropy external dependency

### ISSUE THREAD

**Issue by mpolitzer** [cartesi/machine-emulator-tools#10]
We should either remove `rndaddentropy` completely by initialization entropy at boot. Or create our own tool in this repository (the tool is very simple, just a few lines of code), this would be an improvement to depend less on third party work and simplify tools.

**Comment by edubart** [comment]
After we remove rom, this will be doable at the boot, and I think this is the best option because it will allow us to completely remove this tool.
