### ISSUE TITLE
Provide a CHECKSUM file for released artifacts

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/machine-emulator-tools#19]
## Context

I'm using the .tar.gz artifact released at https://github.com/cartesi/machine-emulator-tools/releases/tag/v0.12.0 and it lacks a CHECKSUM so I can verify the file integrity in my build process.

## Possible solutions

Provide a SHA512SUM file with checksums for the released artifact together with the released artifacts on Github Release page.

**Comment by mpolitzer** [comment]
Providing a file hash can help verify integrity.
For file tempering, however, this is insufficient.

I would recommend having the expected hash in the download script.
